name: Bug Report
description: Report a bug or issue with the SDK
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: dropdown
    id: sdk
    attributes:
      label: Which SDK?
      description: Which SDK is affected?
      options:
        - Python
        - JavaScript/TypeScript
        - Go
        - Rust
        - C
        - Multiple SDKs
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SDK Version
      description: Which version are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The API should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the API...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        from keyvalue import KeyValueClient
        client = KeyValueClient(token="...")
        # code that triggers the bug

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: Ubuntu 22.04
        - Runtime: Python 3.11
        - Additional context...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error messages or stack traces
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided a minimal code sample
          required: false
        - label: I am willing to submit a PR to fix this issue
          required: false
